### PR TITLE
Add visualizer

### PR DESCRIPTION
**Pull request by TimMagoun**
- Use TonioViz as trajectory, landmark, and range visualizer
- Added example and example dataset.
- Depends on TonioViz PR#22 `1d103de6`

### CODE REVIEW

**Comment by TimMagoun** [comment]
TODO: Add docs to readme, add instructions about installing opencv and pangolin (v0.6) which TonioViz depends on

**Comment by alanpapalia** [comment]
In the CMakeLists.txt I set viz to default to on:

`set(ENABLE_VISUALIZATION ON CACHE BOOL "Enable visualization module.")`

This is to make sure that we have the build environment nailed down to perform visualization. If it's a pain to modify the build environments in the github actions then I'm okay turning it off by default and letting interested users follow the instructions to set it up.

**Review by alanpapalia — COMMENTED** [review]
I think it looks great! @TimMagoun can you provide feedback on the changes to the CMakeLists.txt and GitHub workflows to make sure it's of sufficient quality?

Fixed the bug with orientations seemingly pointing the wrong way (is b/c our state variables are actually stored as R^T so they needed to be transposed before viz).

**Comment by TimMagoun** [comment]
LGTM!

**Pull request merged**
