### PR TITLE
add in basic functionality for storing problem data

### PR DESCRIPTION
**Pull request by alanpapalia**
Basic implementations for storing data - is likely necessary for testing pyfg_parse

### CODE REVIEW

**Comment by TimMagoun** [comment]
@alanpapalia Is this ready to merge?

**Comment by alanpapalia** [comment]
Adding quite a bit of testing b/c this is where I feel it's easy to get "bit" by a small misstep. Most of this is covered in the last few pushes, but I want to add a tiny bit more testing before the merge.

**Comment by alanpapalia** [comment]
Mkay I think now we have all of the test coverage I was hoping to get right now -- ready to review/merge from me!

**Review by TimMagoun — APPROVED** [review]
Looks good

**Pull request merged**
